# PyTorch Basics 

In [8]:
import torch

#### scalars

In [10]:
t1=torch.tensor(4.)
print(t1)

tensor(4.)


In [12]:
t1.dtype

torch.float32

#### vectors

In [16]:
t2=torch.tensor([1.0,2,3])
t2

tensor([1., 2., 3.])

#### matrix

In [18]:
t4=torch.tensor([[1,2],[3,4],[5,6]])
t4

tensor([[1, 2],
        [3, 4],
        [5, 6]])

#### 3d array

In [34]:
t5=torch.tensor([[[1,2],[3,4],[5,6]],[[5,6],[7,8],[9,10]]])
t5

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 5,  6],
         [ 7,  8],
         [ 9, 10]]])

In [24]:
t1.shape

torch.Size([])

In [26]:
t2.shape

torch.Size([3])

In [32]:
t4.shape


torch.Size([3, 2])

In [38]:
t5.shape

torch.Size([2, 3, 2])

## Tensor Operations and Gradients

gradient is just another name for derivatives or diffrentation function.

1. gradients are used with matrices

2. derivatives are used with numbers

In [40]:
t1=torch.tensor(4.,requires_grad=True)
t2=torch.tensor(1.,requires_grad=True)
t3=torch.tensor(5)
    

In [54]:
y=t1+t2*t3
# they are like normal arithmetic operations performed on scalars vectors and matrices....

In [55]:
y.backward()

In [58]:
print(t1.grad )
print(t2.grad)
print(t3.grad)

tensor(10.)
tensor(15.)
None


### Torch to Numpy (interoperatablity)

In [60]:
import numpy as np

In [69]:
# from numpy to torch tensor 
x=np.array([[1,2],[3,4]])
y=torch.from_numpy(x)
y.dtype


torch.int32

In [70]:
 torch.tensor(x)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

both the above methods do the same thing that is they convert numpy array to Pytorch tensors but,

1. torch.from_numpy(array) does'nt create a new copy of the 
   array.
2. but torch.tensor(array) creates a new copy of the numpy array

In [71]:
# converting torch tensor to numpy
y.numpy()

array([[1, 2],
       [3, 4]])

# Exercises

In [106]:
x=torch.tensor([[1.,2],[3,4],[5,6]],requires_grad=True)
w=torch.tensor([[2.,4],[7,8],[9,10]],requires_grad=True)
b=torch.tensor([[2.,4],[9,8],[1,2]],requires_grad=True)

In [126]:
y=x**2+w
y=y-b
y=y*y

y.backward()

# error commited for the purpose of understanding        

RuntimeError: grad can be implicitly created only for scalar outputs

In [122]:
for i in y :
    for j in i:
        j.backward()
        break
    break

In [123]:
x.grad

tensor([[16.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]])

In [124]:
w.grad

tensor([[8., 0.],
        [0., 0.],
        [0., 0.]])

In [125]:
b.grad

tensor([[-8., -0.],
        [-0., -0.],
        [-0., -0.]])