In [108]:
import torch
import numpy as np

In [109]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [110]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [111]:
X_train=torch.from_numpy(inputs)
y_train=torch.from_numpy(targets)


In [112]:
weights=torch.randn(2,3,requires_grad=True)
bias=torch.randn(2,requires_grad=True)
weights

tensor([[ 0.5160, -0.9201, -0.5144],
        [ 1.1735,  0.8867,  0.4799]], requires_grad=True)

In [113]:
def model(x):
    val=x @ weights.t()
    return val + bias

In [114]:
z=model(X_train)
z

tensor([[ -46.6004,  165.7621],
        [ -67.4373,  215.5831],
        [-108.7412,  248.7999],
        [  -6.4668,  175.6318],
        [ -89.2367,  199.7399]], grad_fn=<AddBackward0>)

In [115]:
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

# loss function(MSE)


In [116]:
def loss(m1,m2):
    sub=m1-m2
    squr=sub*sub
    return torch.sum(squr)/squr.numel()

In [117]:
losss=loss(z,y_train)
losss

tensor(18363.8848, grad_fn=<DivBackward0>)

# Gradient 

In [118]:
losss.backward()

In [119]:
weights.grad


tensor([[-11395.8096, -14026.5654,  -8326.1270],
        [  9440.7588,   9145.7539,   5789.7314]])

In [130]:
with torch.no_grad():
    weights-=weights.grad * 1e-5
    bias-=bias.grad * 1e-5
    weights.grad.zero_()
    bias.grad.zero_()

In [131]:
mod=model(X_train)
losss=loss(mod,y_train)
print(losss)

tensor(12878.8926, grad_fn=<DivBackward0>)


#  Episodes

In [139]:
for i in range(500):
    mod=model(X_train)
    losss=loss(mod,y_train)
    losss.backward()
    with torch.no_grad():
        weights-=weights.grad * 1e-5
        bias-=bias.grad * 1e-5
        weights.grad.zero_()
        bias.grad.zero_()

print(losss)
print(mod)
print(y_train)

tensor(0.7148, grad_fn=<DivBackward0>)
tensor([[ 57.1169,  70.3568],
        [ 81.9595, 100.3269],
        [119.3316, 133.6626],
        [ 21.2672,  37.2119],
        [101.2828, 118.4346]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
