In [37]:
from torch.utils.data import DataLoader

In [55]:
from torch.utils.data import TensorDataset

In [3]:
import numpy as np

In [15]:
inputs=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]],dtype='float32')

In [16]:
target=np.array([
               [1,2],
               [4,5],
               [7,8]],dtype='float32')

In [20]:
import torch
inpu=torch.from_numpy(inputs)
targe=torch.from_numpy(target)

In [21]:
import torch.nn as nn


In [22]:
model=nn.Linear(3,2)
mod=model(inpu)


In [24]:
loss=nn.MSELoss()

In [66]:
ls=loss(mod,targe)
ls

tensor(34.2183, grad_fn=<MseLossBackward>)

In [33]:
optim=torch.optim.SGD(model.parameters(),lr=1e-5)


In [56]:
ds=TensorDataset(inpu,targe)

In [58]:
for i in ds:
    print(i)

(tensor([1., 2., 3.]), tensor([1., 2.]))
(tensor([4., 5., 6.]), tensor([4., 5.]))
(tensor([7., 8., 9.]), tensor([7., 8.]))


In [60]:
load=DataLoader(ds,batch_size=1,shuffle=True)

In [62]:
for i,j in load:
    print(i)
    print(j)

tensor([[4., 5., 6.]])
tensor([[4., 5.]])
tensor([[7., 8., 9.]])
tensor([[7., 8.]])
tensor([[1., 2., 3.]])
tensor([[1., 2.]])


In [63]:
optim=torch.optim.SGD(model.parameters(),lr=1e-5)
for i,j in load:
    mode=model(i)
    ls=loss(mode,j)
    ls.backward()
    optim.step()

In [64]:
model(inpu)

tensor([[ 1.0808, -0.9573],
        [ 1.6560, -1.9275],
        [ 2.2312, -2.8977]], grad_fn=<AddmmBackward>)

In [65]:
los=loss(model(inpu),targe)
los

tensor(33.9564, grad_fn=<MseLossBackward>)