In [2]:
from torch.utils.data import DataLoader

In [3]:
from torch.utils.data import TensorDataset

In [4]:
import numpy as np

In [5]:
inputs=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]],dtype='float32')

In [6]:
target=np.array([
               [1,2],
               [4,5],
               [7,8]],dtype='float32')

In [7]:
import torch
inpu=torch.from_numpy(inputs)
targe=torch.from_numpy(target)

In [8]:
import torch.nn as nn


In [9]:
model=nn.Linear(3,2)
mod=model(inpu)


In [10]:
loss=nn.MSELoss()

In [11]:
ls=loss(mod,targe)
ls

tensor(23.4827, grad_fn=<MseLossBackward>)

In [12]:
optim=torch.optim.SGD(model.parameters(),lr=1e-5)


In [13]:
ds=TensorDataset(inpu,targe)

In [14]:
for i in ds:
    print(i)

(tensor([1., 2., 3.]), tensor([1., 2.]))
(tensor([4., 5., 6.]), tensor([4., 5.]))
(tensor([7., 8., 9.]), tensor([7., 8.]))


In [15]:
load=DataLoader(ds,batch_size=1,shuffle=True)

In [16]:
for i,j in load:
    print(i)
    print(j)

tensor([[4., 5., 6.]])
tensor([[4., 5.]])
tensor([[7., 8., 9.]])
tensor([[7., 8.]])
tensor([[1., 2., 3.]])
tensor([[1., 2.]])


In [20]:
optim=torch.optim.SGD(model.parameters(),lr=1e-5)
for i in range(300):
    for i,j in load:
        mode=model(i)
        ls=loss(mode,j)
        ls.backward()
        optim.step()
        optim.zero_grad()

In [21]:
model(inpu)

tensor([[2.3773, 1.2825],
        [4.5870, 3.0868],
        [6.7967, 4.8912]], grad_fn=<AddmmBackward>)

In [22]:
los=loss(model(inpu),targe)
los

tensor(2.6872, grad_fn=<MseLossBackward>)